name = "studio-inkless-blog"
compatibility_date = "2024-01-01"

# R2 bucket binding
# In production, you'll bind this through Cloudflare Pages dashboard:
# Settings > Functions > R2 bucket bindings
# Binding name: MY_BUCKET
# Bucket: your-bucket-name

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "blog-404401"
preview_bucket_name = "blog-404401"
